import { THREE } from './ThreeScene.js';
import { getCampaignCompletionRecipe } from './CampaignCompletionLandmarkRecipes.js';

const P={stone:0x625b62,dark:0x24232b,iron:0x454b53,rust:0x874b32,brass:0xb4823e,gold:0xd2a94f,wood:0x65422b,red:0x7d2f35,cloth:0x59657c,bone:0xd0c5a6,water:0x3d7184,green:0x718f4e,silk:0xd6d5ca,void:0x25183f,heart:0x8f263e,fire:0xff8a34,glass:0x91c3c8};
const CONFIG={
'industry.goblin.market':['market',19,14], 'orc.arena.red-pit':['arena',22,17], 'orc.hall.chieftain':['hall',18,14],
'sanctum.circular':['sanctum',22,18], 'sanctum.heart.chamber':['heart',26,20], 'laboratory.summoning.failed':['summoning',18,15],
'laboratory.emergency.way':['way',10,18], 'royal.vault.crown':['vault',16,12], 'royal.banquet.shattered':['banquet',22,16],
'royal.bedchamber':['bedroom',15,12], 'flooded.granary.quiet-teeth':['granary',14,11], 'flooded.wine-cellar':['cellar',15,10],
'fungal.glasshouse.rotten':['glasshouse',16,12], 'fungal.gardener.chamber':['gardener',13,10], 'spider.vault.hosts':['hosts',15,11],
'spider.gallery.spawning':['spawning',16,12]};

export function createCampaignCompletionDiorama(id,context={}){
 const recipe=getCampaignCompletionRecipe(id); if(!recipe)return null;
 const state=recipe.states.includes(context.state)?context.state:recipe.defaultState;
 const root=new THREE.Group(); root.name=`campaign-completion:${id}`; root.userData={assetId:id,state,roomId:recipe.roomId,animatedNodes:[]};
 const [kind,w,d]=CONFIG[id]; floor(root,w,d); BUILD[kind](root,state); return root;
}

const BUILD={
 market:(r,s)=>{for(let i=0;i<8;i++){const g=group('stall-row');g.add(box(3,.18,1.8,'wood',0,.8,0),box(3.4,.16,2.1,i%2?'red':'cloth',0,2.1,0));for(let j=0;j<5;j++)g.add(box(.35,.25,.35,j%2?'brass':'gold',-1.1+j*.55,1,0));g.position.set(-6.4+(i%4)*4.3,0,-4+Math.floor(i/4)*8);r.add(g);}r.add(named(ring(3.2,'brass'),'market-square'));for(let i=0;i<12;i++)r.add(named(box(.5,.35,.7,i%2?'gold':'rust',-3+(i%6)*1.2,.25,-1+Math.floor(i/6)*2),'stolen-goods'));if(s==='orc-taxed')r.add(arch('tax-checkpoint',5.5,3.8));if(s==='burned')embers(r,10);},
 arena:(r,s)=>{const pit=new THREE.Mesh(new THREE.CylinderGeometry(5.2,5.8,1.3,32),mat('rust'));pit.position.y=-.55;pit.name='combat-pit';r.add(pit);for(let t=0;t<3;t++)for(let i=0;i<18;i++){const a=i*Math.PI*2/18;const seat=named(box(1.5,.4,.8,'stone'),'spectator-stands');seat.position.set(Math.cos(a)*(7.2+t),.25+t*.45,Math.sin(a)*(7.2+t));seat.rotation.y=-a;r.add(seat);}for(const x of [-8.5,8.5]){const g=arch('fighter-gate',3.2,3.2);g.position.x=x;g.rotation.y=Math.PI/2;r.add(g);}r.add(named(throne(0,-7),'chieftain-dais'));if(s==='chieftain-challenge')animate(r,named(ring(4,'fire'),'challenge-ring'));if(s==='liberated')r.add(named(box(5,2.2,.12,'cloth',0,3,-8),'liberation-banner'));},
 hall:(r,s)=>{r.add(throne(0,-5));r.add(named(box(8,.4,3,'wood',0,1,1),'council-table'));for(let i=0;i<8;i++)r.add(named(sphere(.35,'bone',-6+i*1.7,2.8,6),'trophy-wall'));r.add(named(box(2.6,.65,2.6,'dark',0,.32,-1),'judgement-stone'));banner(r,s==='leaderless'?'cloth':'red');},
 sanctum:(r,s)=>{for(const rad of [3,6,9]){const q=named(ring(rad,rad===3?'gold':'void'),rad===3?'inner-ring':'outer-ring');q.rotation.x=Math.PI/2;animate(r,q);}r.add(named(cyl(2.2,2.8,1.1,'stone',0,.55,0),'ritual-core'));for(let i=0;i<4;i++){const a=i*Math.PI/2;r.add(named(box(2.4,1.4,1.6,i%2?'red':'brass',Math.cos(a)*7.4,.7,Math.sin(a)*7.4),'faction-altar'));}if(s==='ritual-active')motes(r,16,'ritual-mote');if(s==='fractured')for(let i=0;i<7;i++)animate(r,named(box(.35,3.4,.5,'void',-5+i*1.7,1.7,(i%2?1:-1)*2.5),'fracture-rift'));},
 heart:(r,s)=>{r.add(named(cyl(5.2,6.2,1.5,'stone',0,.75,0),'boss-dais'));const h=group('heart-core');h.add(sphere(2.4,'heart',0,5,0),sphere(1.7,'heart',-1.4,4.8,.3),sphere(1.4,'heart',1.5,4.6,-.2));for(let i=0;i<8;i++){const a=cyl(.28,.5,6.5,'heart');a.rotation.z=Math.PI/2+(i-4)*.08;a.position.set(Math.cos(i)*2.2,5+Math.sin(i),Math.sin(i)*2.2);h.add(a);}animate(r,h);for(let i=0;i<4;i++){const a=i*Math.PI/2;const b=named(box(3.8,.35,1.3,'stone',Math.cos(a)*7.2,.35,Math.sin(a)*7.2),'artery-bridge');b.rotation.y=-a;r.add(b);}if(s==='awakened')motes(r,18,'heart-spark');if(s==='claimed')for(let i=0;i<4;i++)r.add(named(box(1.4,4,.12,i%2?'gold':'cloth',-7+i*4.6,3,-8),'claim-standard'));if(s==='collapsed'){h.rotation.z=.45;h.position.y=-2;}},
 summoning:(r,s)=>{const q=named(ring(5.5,'void'),'summoning-circle');q.rotation.x=Math.PI/2;r.add(q);for(let i=0;i<6;i++){const a=i*Math.PI/3;r.add(named(cyl(.35,.55,4.4,'brass',Math.cos(a)*6.5,2.2,Math.sin(a)*5),'containment-pylon'));}r.add(named(cyl(2,2.4,1,'void',0,.5,0),'death-energy-well'));r.add(named(box(3,1.2,1.4,'iron',6,.6,-5),'stabilizer-console'));if(s==='breached')animate(r,named(sphere(2.3,'void',0,4,0),'wraith-breach'));},
 way:(r,s)=>{for(const side of [-1,1])for(let i=0;i<8;i++)r.add(box(.8,3.2,1.5,'stone',side*4.4,1.6,-7+i*2));const d=arch('blast-door',7,5);d.position.z=-8;if(s==='opened')d.position.y=3.8;r.add(d);for(let i=0;i<8;i++)r.add(named(box(.16,.18,1.6,'brass',i%2?-1.2:1.2,.18,-6+i*1.7),'escape-rail'));animate(r,named(sphere(.35,s==='sealed'?'red':'fire',0,4.8,-6.5),'warning-beacon'));if(s==='collapsed')rubble(r,10,'collapse-zone');},
 vault:(r,s)=>{const d=arch('vault-door',6.5,5.2);d.position.z=-5.5;if(s==='opened')d.position.y=3.8;r.add(d);for(let i=0;i<6;i++)r.add(named(box(2.1,2.4,.7,'wood',-6+i%3*6,1.2,1+Math.floor(i/3)*4),'treasure-rack'));r.add(named(cyl(1.5,2,1.8,'stone',0,.9,0),'relic-pedestal'));if(s!=='stripped'){const c=named(ring(1,'gold'),'crown-vault');c.rotation.x=Math.PI/2;c.position.y=2;r.add(c);}},
 banquet:(r,s)=>{r.add(named(box(12,.8,3,'wood',0,.4,-6),'high-table'));for(let row=0;row<3;row++)r.add(named(box(14,.5,1.8,'wood',0,.8,-2+row*4),'banquet-row'));r.add(arch('settlement-hearth',4,4.5));if(s==='haunted')motes(r,10,'ghost-dais');if(s==='occupied')for(let i=0;i<4;i++)banner(r,i%2?'red':'cloth',-7+i*4.5);},
 bedroom:(r,s)=>{const b=group('royal-bed');b.add(box(7,.8,4,'wood',0,.4,0),box(6.5,.5,3.5,'red',0,1,0));r.add(b);r.add(named(box(3,4,1.2,'wood',5.4,2,3.6),'relic-cabinet'));r.add(named(box(.2,4.5,6,'cloth',-5.5,2.25,1.5),'privacy-screen'));const p=named(box(3,4,.3,'stone',0,2,-5.7),'secret-panel');if(s==='searched')p.rotation.y=.8;r.add(p);if(s==='sanctuary')motes(r,6,'sanctuary-lamp');},
 granary:(r,s)=>{for(let i=0;i<6;i++)r.add(named(cyl(1.2,1.5,5.5,'wood',-5+(i%3)*5,2.75,-2.8+Math.floor(i/3)*5.6),'grain-silo'));r.add(named(box(5,.25,.3,'iron',-3.8,5.8,4.5),'loading-crane'));if(s==='rat-dominated')motes(r,16,'rat-warren');if(s==='restored')r.add(named(box(7,1,2,'wood',0,.5,4.3),'restoration-table'));},
 cellar:(r,s)=>{for(let row=0;row<2;row++)for(let i=0;i<8;i++){const b=named(cyl(.65,.65,1.8,'wood',-5.8+i*1.65,.8,-3+row*6),'barrel-rack');b.rotation.z=Math.PI/2;r.add(b);}const w=named(box(13,.35,5,'water',0,.16,0),'flood-basin');w.visible=s==='flooded';animate(r,w);r.add(named(box(5,.6,2,'wood',0,.8,0),'tasting-table'));if(s==='fermenting-colony')motes(r,12,'fungal-vat');},
 glasshouse:(r,s)=>{for(let i=0;i<7;i++){const a=arch('glasshouse-frame',12,5);a.position.z=-5+i*1.7;a.rotation.y=Math.PI/2;r.add(a);}for(let row=0;row<3;row++){r.add(named(box(12,.8,2,'wood',0,.4,-3.8+row*3.8),'cultivation-bed'));for(let i=0;i<8;i++)animate(r,named(sphere(.3+(i%3)*.12,'green',-5.2+i*1.5,1.1,-3.8+row*3.8),'spore-canopy'));}if(s==='shattered')rubble(r,15,'shatter-zone','glass');},
 gardener:(r,s)=>{r.add(named(box(6,.8,3,'wood',-2,.4,0),'gardener-cot'));r.add(named(box(4,1,2,'wood',4,.5,-3),'medicine-table'));const t=group('root-throne');for(let i=0;i<8;i++){const q=cyl(.18,.35,4,'green');q.rotation.z=(i-4)*.18;q.position.set((i-4)*.35,2,0);t.add(q);}t.position.set(3,0,2);r.add(t);if(s==='awakened')animate(r,named(ring(2.5,'gold'),'rest-circle'));if(s==='consumed')motes(r,14,'consumption-core');},
 hosts:(r,s)=>{for(let row=0;row<2;row++)for(let i=0;i<6;i++){const c=group('host-cocoon');c.add(sphere(.7,'silk',0,1.8,0),cyl(.35,.6,2.5,'silk',0,.5,0));c.position.set(-5+i*2,-.2,-3+row*6);if(s==='rescued')c.rotation.z=1.4;if(s==='empty-cocoons')c.scale.y=.55;r.add(c);}r.add(named(box(13,.3,.4,'iron',0,5,0),'silk-hoist'));r.add(named(box(5,.5,3,'wood',0,.25,0),'rescue-platform'));},
 spawning:(r,s)=>{for(let row=0;row<4;row++)for(let i=0;i<7;i++){const e=named(sphere(.35+(i%2)*.15,'silk',-6+i*2,.45,-4.5+row*3),'egg-clutch');if(s==='destroyed')e.scale.y=.35;animate(r,e);}for(let i=0;i<8;i++){const w=named(ring(1.4+i*.25,'silk'),'nursery-web');w.rotation.x=Math.PI/2;w.position.y=2+i*.35;r.add(w);}r.add(named(cyl(2,2.5,1.3,'bone',0,.65,-4.5),'brood-altar'));if(s==='overpopulated')motes(r,12,'hatch-lane');if(s==='destroyed')embers(r,10);}
};

export function animateCampaignCompletion(root,t){for(const [i,n] of (root.userData?.animatedNodes??[]).entries()){const p=1+Math.sin(t*(1.2+(i%4)*.25)+i)*.06;n.scale.setScalar(p);n.rotation.y+=.002*(i%3+1);}}
function floor(r,w,d){r.add(box(w,.16,d,'dark',0,0,0));}
function group(n){const g=new THREE.Group();g.name=n;return g;} function named(o,n){o.name=n;return o;} function animate(r,o){r.userData.animatedNodes.push(o);r.add(o);return o;}
function mat(n){return new THREE.MeshStandardMaterial({color:P[n]??P.stone,roughness:n==='iron'||n==='brass'||n==='gold'?.45:.9,metalness:['iron','brass','gold'].includes(n)?.65:.03,transparent:['water','glass','void'].includes(n),opacity:n==='glass'?.42:n==='water'?.58:n==='void'?.78:1,emissive:['fire','heart','void'].includes(n)?P[n]:0,emissiveIntensity:.35});}
function box(w,h,d,m,x=0,y=0,z=0){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(m));q.position.set(x,y,z);return q;} function sphere(a,m,x=0,y=0,z=0){const q=new THREE.Mesh(new THREE.SphereGeometry(a,12,8),mat(m));q.position.set(x,y,z);return q;} function cyl(a,b,h,m,x=0,y=0,z=0){const q=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,12),mat(m));q.position.set(x,y,z);return q;} function ring(a,m){return new THREE.Mesh(new THREE.TorusGeometry(a,.18,8,32),mat(m));}
function arch(n,w,h){const g=group(n);g.add(box(w,.4,.6,'iron',0,h,0),box(.5,h,.6,'iron',-w/2,h/2,0),box(.5,h,.6,'iron',w/2,h/2,0));return g;} function throne(x,z){const g=group('war-throne');g.add(box(3,1,2.4,'dark',0,.5,0),box(2.8,4,.8,'wood',0,2.4,-.8));g.position.set(x,0,z);return g;}
function banner(r,m='red',x=0){r.add(named(box(1.6,3,.1,m,x,3.2,-6.5),'faction-banner'));} function motes(r,n,name){for(let i=0;i<n;i++)animate(r,named(sphere(.14+(i%3)*.05,i%2?'fire':'void',Math.cos(i)*5,1+(i%6),Math.sin(i)*4),name));} function embers(r,n){for(let i=0;i<n;i++)animate(r,named(sphere(.12,'fire',-6+i*1.3,.3,(i%3-1)*3),'fire-target'));} function rubble(r,n,name,m='stone'){for(let i=0;i<n;i++)r.add(named(box(.8,.5,1.1,m,-6+(i%7)*2,.25,-3+Math.floor(i/7)*6),name));}
