import { recomputeHeroStats } from './HeroSystem.js';
export class HeroHoardSystem{
 constructor({onEvent=()=>{}}={}){this.onEvent=onEvent;this.shells=[];this.projectiles=[];this.sequence=0;this.scavengeClock=0;}
 update(dt,sim){this.scavengeClock+=dt;for(const shell of this.shells)shell.remaining-=dt;this.shells=this.shells.filter(item=>item.remaining>0&&item.hp>0);for(const p of this.projectiles){p.remaining-=dt;p.progress=Math.min(1,1-p.remaining/p.duration);if(p.remaining<=0&&!p.impacted){p.impacted=true;const target=(sim?.agents??[]).find(a=>a.id===p.targetId);const owner=(sim?.agents??[]).find(a=>a.id===p.ownerId);if(target?.alive!==false)sim?.applyCombatDamage?.(owner,target,p.damage,{projectileType:'relic',heroSkill:true});}}this.projectiles=this.projectiles.filter(item=>item.remaining>0&&!item.impacted);
  for(const hero of(sim?.agents??[]).filter(a=>a.heroId==='hero.goldcrown-back'&&a.alive!==false)){tickStatus(hero,'royalMolt',dt,()=>{delete hero.heroStatModifiers.royalMolt;hero.heroVariant='hoard-carapace';recomputeHeroStats(hero);});if(this.scavengeClock>=4&&!hero.heroCast&&!hero.combat)this.passiveScavenge(hero,sim);}
  if(this.scavengeClock>=4)this.scavengeClock=0;
 }
 passiveScavenge(owner,sim){const corpse=(sim?.corpses??[]).find(item=>item.roomId===owner.roomId&&!item.consumed);const prop=(sim?.props??[]).find(item=>item.roomId===owner.roomId&&!item.opened&&!item.consumed&&/treasure|relic|armor|crown|weapon/.test(`${item.type??''} ${item.label??''}`));const item=prop??corpse;if(!item)return false;item.consumed=true;item.hidden=true;owner.swallowedTrophies=[...(owner.swallowedTrophies??[]),{id:item.id,type:item.type??'corpse'}].slice(-10);owner.hoardArmor=Math.min(8,(owner.hoardArmor??0)+1);owner.heroStatModifiers.hoard={armor:owner.hoardArmor,attack:0,courage:1,speedMultiplier:Math.max(.78,1-owner.hoardArmor*.02),interruptResistance:Math.min(.3,owner.hoardArmor*.035)};owner.heroVariant=`hoard-${Math.min(3,Math.ceil(owner.hoardArmor/3))}`;recomputeHeroStats(owner);return true;}
 boneRakeCharge(owner,targetId,effect,sim){const targets=lineTargets(owner,targetId,sim,effect.length??6,effect.width??1.7);for(const target of targets.slice(0,4)){sim?.applyCombatDamage?.(owner,target,effect.damage??17,{melee:true,heroSkill:true});sim?.heroPhysicsSystem?.applyImpulse?.(target,directionTo(owner,target),effect.impulse??6.5,{sourceId:owner.id,roomId:owner.roomId,kind:'bone-rake-charge'});const stolen=Math.min(effect.armorSteal??1,target.armor??0);target.armor=Math.max(0,(target.armor??0)-stolen);owner.hoardArmor=Math.min(8,(owner.hoardArmor??0)+stolen);}owner.heroStatModifiers.hoard={armor:owner.hoardArmor??0,attack:0,courage:1,speedMultiplier:Math.max(.78,1-(owner.hoardArmor??0)*.02),interruptResistance:Math.min(.3,(owner.hoardArmor??0)*.035)};recomputeHeroStats(owner);return targets.length>0;}
 trophyVolley(owner,effect,sim){const hostiles=roomHostiles(owner,sim).sort((a,b)=>power(b)-power(a));const shots=Math.min(effect.maximum??5,hostiles.length,Math.max(1,owner.hoardArmor??0));for(let i=0;i<shots;i++){const target=hostiles[i%hostiles.length];this.projectiles.push({id:`relic-shot-${this.sequence++}`,kind:'relic-projectile',ownerId:owner.id,roomId:owner.roomId,targetId:target.id,damage:effect.damage??8,duration:.7+i*.08,remaining:.7+i*.08,progress:0,from:{x:0,y:1.4,z:0},to:{x:target.roomCell?.x??0,y:.7,z:target.roomCell?.z??0}});}owner.hoardArmor=Math.max(0,(owner.hoardArmor??0)-shots*(effect.armorCostPerShot??1));owner.heroStatModifiers.hoard={armor:owner.hoardArmor,attack:0,courage:1,speedMultiplier:Math.max(.78,1-owner.hoardArmor*.02),interruptResistance:Math.min(.3,owner.hoardArmor*.035)};recomputeHeroStats(owner);return shots>0;}
 royalMolt(owner,effect,sim){const trophies=[...(owner.swallowedTrophies??[])];const shell={id:`relic-shell-${this.sequence++}`,kind:'relic-shell',ownerId:owner.id,roomId:owner.roomId,hp:effect.shellHp??70,maxHp:effect.shellHp??70,remaining:60,trophies:trophies.slice(-8),ox:0,oz:0};this.shells.push(shell);const release=Math.min(effect.lootRelease??4,trophies.length);for(let i=0;i<release;i++)sim?.props?.push?.({id:`molted-relic-${this.sequence++}`,type:'treasure',label:'Molted Royal Relic',roomId:owner.roomId,opened:false,sourceHeroId:owner.heroId});owner.swallowedTrophies=[];owner.hoardArmor=0;owner.moltCount=(owner.moltCount??0)+1;owner.heroStatuses.royalMolt={remaining:effect.duration??17};owner.heroStatModifiers.hoard={armor:0,attack:0,courage:0,speedMultiplier:1,interruptResistance:0};owner.heroStatModifiers.royalMolt={armor:-2,attack:effect.attackBonus??5,courage:4,speedMultiplier:effect.speedMultiplier??1.35,interruptResistance:.2};owner.heroVariant='ravenous-molt';recomputeHeroStats(owner);return true;}
 modifyIncomingDamage(source,target,amount){if(target?.heroId!=='hero.goldcrown-back')return amount;return amount*Math.max(.55,1-(target.hoardArmor??0)*.045);}
 snapshot(){return{shells:this.shells.map(copy),projectiles:this.projectiles.map(copy)};}
 metrics(){return{heroHoardShells:this.shells.length,heroRelicProjectiles:this.projectiles.length};}
}
function tickStatus(agent,key,dt,onExpire){const status=agent.heroStatuses?.[key];if(!status)return;status.remaining-=dt;if(status.remaining<=0){delete agent.heroStatuses[key];onExpire?.();}}
function lineTargets(owner,targetId,sim,length,width){const list=roomHostiles(owner,sim),primary=list.find(a=>a.id===targetId)??list[0],o=point(owner),q=point(primary??{roomCell:{x:o.x,z:o.z+1}}),dx=q.x-o.x,dz=q.z-o.z,m=Math.hypot(dx,dz)||1,ux=dx/m,uz=dz/m;return list.filter(a=>{const p=point(a),rx=p.x-o.x,rz=p.z-o.z,along=rx*ux+rz*uz,side=Math.abs(rx*-uz+rz*ux);return along>=0&&along<=length&&side<=width;});}
function roomHostiles(owner,sim){return(sim?.agents??[]).filter(a=>a.id!==owner.id&&a.alive!==false&&a.roomId===owner.roomId&&factionOf(a)!==factionOf(owner));}
function point(a){return{x:a?.roomCell?.x??0,z:a?.roomCell?.z??0};}function directionTo(a,b){const p=point(a),q=point(b);return{x:q.x-p.x,z:q.z-p.z};}function factionOf(a){return a?.ecologyFaction??a?.factionId??a?.faction??null;}function power(a){return(a.hp??0)+(a.attack??0)*4;}function copy(v){return JSON.parse(JSON.stringify(v));}
